# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Радио Лунный Муравей
tagline:             Некоммерческая радиостанция космической направленности
url:                 "http://moon-ant.com"
paginate:            10
baseurl:             "http://moon-ant.com"


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
