# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Радио Лунный Муравей
tagline:             Некоммерческая радиостанция космической направленности
url:
paginate:            5
# baseurl:             "http://tretten.github.io/moon-ant.com/"


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
